;;; -*- Lisp -*-

(defpackage "DUAL-NUMBERS"
  (:shadowing-import-from "GENERIC-ARITHMETIC"
   "+" "-" "*" "/" "<" "<=" "=" ">" ">=" "/="
   "1+" "1-"
   "ABS"
   "ACOS"
   "ACOSH"
   "ASIN"
   "ASINH"
   "ATAN"
   "ATANH"
   "CEILING"
   "CIS"
   "COMPLEX"
   "CONJUGATE"
   "COS"
   "COSH"
   "DECODE-FLOAT"
   "DENOMINATOR"
   "EXP"
   "EXPT"
   "FCEILING"
   "FFLOOR"
   "FLOAT"
   "FLOAT-DIGITS"
   "FLOAT-PRECISION"
   "FLOAT-RADIX"
   "FLOAT-SIGN"
   "FLOOR"
   "FROUND"
   "FTRUNCATE"
   "IMAGPART"
   "INTEGER-DECODE-FLOAT"
   "LOG"
   "MAX"
   "MIN"
   "MOD"
   "NUMERATOR"
   "PHASE"
   "RANDOM"
   "RATIONAL"
   "RATIONALIZE"
   "REALPART"
   "REM"
   "ROUND"
   "SCALE-FLOAT"
   "SIGNUM"
   "SIN"
   "SINH"
   "SQRT"
   "TAN"
   "TANH"
   "TRUNCATE"
   "ZEROP")                                    
  (:export "MAKE-DUAL"
           "DERIVATIVE"
           "DUAL-NUMBER"
           "DUAL?"
           "STANDARD-PART"
           "INFINITESIMAL-PART")
  (:use "COMMON-LISP" "GENERIC-ARITHMETIC"))

(defpackage "DUAL-NUMBERS-TESTS"
  (:shadowing-import-from "GENERIC-ARITHMETIC"
   "+" "-" "*" "/" "<" "<=" "=" ">" ">=" "/="
   "1+" "1-"
   "ABS"
   "ACOS"
   "ACOSH"
   "ASIN"
   "ASINH"
   "ATAN"
   "ATANH"
   "CEILING"
   "CIS"
   "COMPLEX"
   "CONJUGATE"
   "COS"
   "COSH"
   "DECODE-FLOAT"
   "DENOMINATOR"
   "EXP"
   "EXPT"
   "FCEILING"
   "FFLOOR"
   "FLOAT"
   "FLOAT-DIGITS"
   "FLOAT-PRECISION"
   "FLOAT-RADIX"
   "FLOAT-SIGN"
   "FLOOR"
   "FROUND"
   "FTRUNCATE"
   "IMAGPART"
   "INTEGER-DECODE-FLOAT"
   "LOG"
   "MAX"
   "MIN"
   "MOD"
   "NUMERATOR"
   "PHASE"
   "RANDOM"
   "RATIONAL"
   "RATIONALIZE"
   "REALPART"
   "REM"
   "ROUND"
   "SCALE-FLOAT"
   "SIGNUM"
   "SIN"
   "SINH"
   "SQRT"
   "TAN"
   "TANH"
   "TRUNCATE"
   "ZEROP")                                    
  (:use "COMMON-LISP" "DUAL-NUMBERS" "GENERIC-ARITHMETIC"))
